version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - VIDEO_SDK_MASTER_KEY=changeme
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379" 